### ISSUE TITLE
Potential bug with monotonic constraint

### ISSUE THREAD

**Issue by zorian15** [matsengrp/torchdms#154]
I've noticed that whenever we impose some sort of constraint on monotonicity of the `g` functions in `torchdms`, our models always fail to train (at least in every instance I've tried to do such) -- not sure why this is, but raising an issue so I don't forget to come back to it at a better time.

I ran a quick experiment on Tyler's RBD data (which I had to re-prep on `/fh/fast/` due to some things added to `torchdms` since then that broke things), results can be found [here](https://github.com/matsengrp/torchdms-experiments/tree/cgg-models/experiments/2021-12-20-mono-bug-search).

Some examples though --

Without monotonic constraints on `g`:

<img width="1030" alt="Screen Shot 2021-12-20 at 1 41 30 PM" src="https://user-images.githubusercontent.com/29761930/146816747-3205fc8f-086f-4ba8-bb52-e7c19ea46068.png">

With monotonic constraints on `g`:
<img width="964" alt="Screen Shot 2021-12-20 at 1 41 57 PM" src="https://user-images.githubusercontent.com/29761930/146816800-bb95cbf9-68d0-4c5c-9f4e-de64f3a7cb5c.png">

**NOTE:** I only trained these models for 100 epochs and no independent starts and a very small `g()`, as the purpose was to see if things broke when a monotonic constraint was added.

**Comment by jgallowa07** [comment]
I've implemented testing to make sure this is doing the right thing. But ultimately, the problem here is because we're not allowing for bias parameters (by default) in the non-linearity. We then constrain positive weights, and in this case, a ReLU activation. Meaning the network can only predict positive values. It's best solution, then is to have negative latent phenotypes, which get floored to exactly 0 in the activation. I'm working on a PR, but the solution will essentially be to not allow for any activation which cannot be negative. 

One nice activation in place of ReLU would be [PReLU](https://pytorch.org/docs/stable/generated/torch.nn.PReLU.html#torch.nn.PReLU)
